"""
services/biometrics.py — Backend biometric score evaluation.

Handles validation and anomaly detection for biometric trust scores
generated by the frontend Web Worker.
"""

from typing import List, Dict, Any, Optional
import logging

logger = logging.getLogger(__name__)


class BiometricProcessor:
    """
    Handles backend validation and storage of the biometric scores
    generated by the frontend Web Worker.
    """

    # Thresholds
    CRITICAL_THRESHOLD = 40
    WARNING_THRESHOLD = 65
    SUDDEN_DROP_THRESHOLD = 30

    def __init__(self):
        self._baseline_scores: Dict[str, float] = {}  # user_id -> baseline avg

    def evaluate_score(
        self,
        current_score: int,
        history: List[int],
        user_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Evaluate sudden drops in biometrics compared to historical average.

        Returns:
            dict with keys:
              - action: OK | REQUIRE_STEP_UP | KILL_SESSION
              - reason: explanation string (if action != OK)
              - confidence: 0-100 confidence in the assessment
        """
        # Critical drop — immediately kill session
        if current_score < self.CRITICAL_THRESHOLD:
            logger.warning(
                f"CRITICAL biometric drop for user={user_id}: score={current_score}"
            )
            return {
                "action": "KILL_SESSION",
                "reason": "CRITICAL_BIOMETRIC_DROP",
                "confidence": 95,
                "score": current_score,
            }

        # Low score — require step-up auth
        if current_score < self.WARNING_THRESHOLD:
            logger.info(
                f"Low biometric score for user={user_id}: score={current_score}"
            )
            return {
                "action": "REQUIRE_STEP_UP",
                "reason": "LOW_BIOMETRIC_CONFIDENCE",
                "confidence": 80,
                "score": current_score,
            }

        # Check for sudden drops if we have history
        if not history:
            return {"action": "OK", "score": current_score, "confidence": 50}

        avg = sum(history) / len(history)
        drop = avg - current_score

        # Update user baseline if provided
        if user_id:
            if user_id not in self._baseline_scores:
                self._baseline_scores[user_id] = avg
            else:
                # Exponential moving average
                self._baseline_scores[user_id] = (
                    self._baseline_scores[user_id] * 0.9 + avg * 0.1
                )

        if drop > self.SUDDEN_DROP_THRESHOLD:
            logger.warning(
                f"Sudden biometric deviation for user={user_id}: "
                f"drop={drop:.1f}, avg={avg:.1f}, current={current_score}"
            )
            return {
                "action": "REQUIRE_STEP_UP",
                "reason": "SUDDEN_BIOMETRIC_DEVIATION",
                "confidence": 75,
                "score": current_score,
                "drop": round(drop, 1),
                "avg": round(avg, 1),
            }

        # Check variance for erratic behavior
        if len(history) >= 5:
            variance = sum((s - avg) ** 2 for s in history[-5:]) / 5
            if variance > 400:  # High variance indicates erratic behavior
                logger.info(
                    f"Erratic biometric pattern for user={user_id}: variance={variance:.1f}"
                )
                return {
                    "action": "REQUIRE_STEP_UP",
                    "reason": "ERRATIC_BIOMETRIC_PATTERN",
                    "confidence": 60,
                    "score": current_score,
                    "variance": round(variance, 1),
                }

        return {"action": "OK", "score": current_score, "confidence": 90}

    def get_user_baseline(self, user_id: str) -> Optional[float]:
        """Get the stored baseline score for a user."""
        return self._baseline_scores.get(user_id)

    def reset_baseline(self, user_id: str):
        """Reset a user's biometric baseline (e.g., after password change)."""
        self._baseline_scores.pop(user_id, None)


# Singleton instance
biometric_processor = BiometricProcessor()
